// типы экшенов
export const LOAD_LIST = 'LOAD_LIST';
export const LOAD_LIST_SUCCESS = 'LOAD_LIST_SUCCESS';
export const LOAD_LIST_FAILED = 'LOAD_LIST_FAILED';
export const LOAD_DESCRIPTION = 'LOAD_DESCRIPTION';
export const LOAD_DESCRIPTION_SUCCESS = 'LOAD_DESCRIPTION_SUCCESS';